---
deployment:
  tasks:
    - /bin/cp -R /home/kiarrapr/repositories/API-KosKuy-PAA/. /home/kiarrapr/apikoskuy.kiarrapro.id
    - /usr/local/bin/php /home/kiarrapr/apikoskuy.kiarrapro.id/artisan config:clear
    - /usr/local/bin/php /home/kiarrapr/apikoskuy.kiarrapro.id/artisan cache:clear
    - /usr/local/bin/php /home/kiarrapr/apikoskuy.kiarrapro.id/artisan route:clear
    - /usr/local/bin/php /home/kiarrapr/apikoskuy.kiarrapro.id/artisan view:clear
